### PR TITLE
HAL for UART.

### PR DESCRIPTION
**Pull request by mkiiskila**
Implementations for native and STM32F3xx for now.

### CODE REVIEW

**Comment by mkiiskila** [comment]
We want users of interrupts to set the priority to something meaningful.If priority is not set, it should be lowest priority, not the highest possible. Therefore the initialization.

**Comment by wes3** [comment]
All right, I was going to complain about something but I just re-read the cortex-m documentation regarding interrupts at the same priority level. I was worried that an exception with interrupt priority 0xff could call a routine that causes a context switch (which sets the pending status of the PendSV interrupt). I did not want PendSV to preempt the current exception and it will not; it will just be pending.

Consider the following case though: an interrupt at priority 0xff does something that causes PendSV to be pending as well as another interrupt which is at priority 0xff. In this case, the PendSV interrupt will execute prior to the other interrupt as the interrupt number of PendSV is lower than the other IRQ (well, assume that is the case for this example).

I had not originally considered this case so I am not sure if our context switch code is equipped to deal with this situation. That is why I was going to suggest defaulting all other interrupts to a priority level greater than PendSV (and possibly even SysTick).

**Comment by mkiiskila** [comment]
Having PendSV execute before some other interrupt handler is be ok. It's no different than slight timing difference with arrival of other interrupts.
The scenario you're describing here is not a very common.

**Comment by mkiiskila** [comment]
Yes, as it's implemented now, interrupt when a byte arrives.

**Pull request merged**
